export const BASE = {
  edgeLow: 0.34,
  edgeHigh: 0.66,
  valley: 0.7,
  gloss: 0.08,
  glossSharpness: 30,
  rim: 0,
  ambient: 0.95,
  outline: 0,
  wobble: 0.15,
  wobbleSpeed: 1,
  wobbleScale: 2.2,
  pixel: 1,
  dither: 0,
  ditherScale: 2,
  levels: 32,
  alphaDither: 0,
  halftone: 0,
  halftoneSize: 10,
  mono: 0,
  hue: 0,
  saturation: 1.1,
  contrast: 1,
  grain: 0.04,
  grainSpeed: 12,
  aberration: 0,
  jellyStiffness: 70,
  jellyDamping: 7,
  lean: 0.24,
  scrollKick: 0.05,
  parallax: 0.05,
  followRate: 5,
  bloomSeconds: 1.7,
  spinSpeed: 1,
  breathe: 0.05,
  petals: 4,
  petalSize: 1,
  petalReach: 1,
  flowerScale: 1,
  coreSize: 1,
  customBackground: false,
  background: "#f2f5fa",
  textColor: "#111111",
  subject: 0,
  layout: 0,
  cellSize: 150,
  jitter: 0,
  sizeVar: 0.3,
  density: 1,
  elementScale: 0.45,
  drift: 0.15,
  layoutSpin: 0.25,
  lobeShape: 2,
  gridMode: 0,
  gridSize: 40,
  gridWarp: 0.6,
  gridStrength: 0.35,
  gridReveal: 0.5,
};

export const PRESETS = {
  "Flower Wall": {
    layout: 2,
    cellSize: 150,
    jitter: 0.08,
    sizeVar: 0.3,
    density: 1,
    elementScale: 0.44,
    petals: 8,
    valley: 0.5,
    saturation: 1.2,
  },
  "Wild Meadow": {
    layout: 3,
    cellSize: 190,
    jitter: 0.85,
    sizeVar: 0.75,
    density: 0.55,
    elementScale: 0.5,
    petals: 6,
    valley: 0.5,
    saturation: 1.25,
  },
  "Flower Rain": {
    layout: 4,
    cellSize: 170,
    jitter: 0,
    sizeVar: 0.3,
    density: 0.9,
    elementScale: 0.42,
    drift: 0.12,
    petals: 5,
    valley: 0.5,
    saturation: 1.25,
  },
  "Pixel Wall": {
    layout: 1,
    cellSize: 150,
    jitter: 0,
    sizeVar: 0.35,
    density: 1,
    elementScale: 0.42,
    pixel: 12,
    levels: 6,
    dither: 0.5,
    ditherScale: 2,
    saturation: 1.5,
    petals: 4,
  },
  "Night Garden": {
    layout: 2,
    cellSize: 150,
    jitter: 0.08,
    sizeVar: 0.3,
    density: 1,
    elementScale: 0.44,
    petals: 8,
    valley: 0.5,
    customBackground: true,
    background: "#07060f",
    textColor: "#f4f1ff",
    saturation: 1.7,
    contrast: 1.2,
  },
  "Candy Field": {
    layout: 1,
    cellSize: 140,
    jitter: 0,
    sizeVar: 0.35,
    density: 1,
    elementScale: 0.46,
    petals: 6,
    hue: 18,
    saturation: 1.3,
    customBackground: true,
    background: "#ffe9f3",
    textColor: "#3b1f4a",
  },
  "Garden Poster": {
    layout: 5,
    petals: 8,
    valley: 0.5,
    saturation: 1.25,
    wobble: 0.1,
  },
  "Pixel Arcade": { pixel: 12, levels: 6, dither: 0.5, ditherScale: 2, saturation: 1.5 },
  "Pixel Night": {
    pixel: 8,
    levels: 5,
    dither: 0.6,
    ditherScale: 2,
    saturation: 1.7,
    customBackground: true,
    background: "#0b0a1a",
    textColor: "#f2eeff",
  },
  "Pixel Candy": {
    pixel: 16,
    levels: 4,
    dither: 0.4,
    ditherScale: 3,
    saturation: 1.4,
    hue: 18,
    customBackground: true,
    background: "#ffe9f3",
    textColor: "#3b1f4a",
  },
  "Pixel Bits": { pixel: 5, levels: 8, dither: 0.8, ditherScale: 2, saturation: 1.3, petals: 6 },
  "Dot Matrix": {
    gridMode: 1,
    gridSize: 30,
    gridStrength: 0.3,
    gridReveal: 0.9,
    gridWarp: 1.1,
    pixel: 10,
    levels: 6,
    dither: 0.5,
    saturation: 1.5,
  },
  Gameboy: {
    customBackground: true,
    background: "#cdd8a0",
    textColor: "#0f380f",
    pixel: 6,
    mono: 1,
    levels: 4,
    dither: 1,
    ditherScale: 2,
    grain: 0.02,
  },
  "Dither Print": { dither: 1, levels: 4, ditherScale: 3, grain: 0.06, contrast: 1.1 },
  Newsprint: {
    customBackground: true,
    background: "#efe6d2",
    textColor: "#1a1814",
    halftone: 1,
    halftoneSize: 8,
    saturation: 0.75,
    contrast: 1.2,
    grain: 0.12,
  },
  "Riso Zine": {
    customBackground: true,
    background: "#f4ecd8",
    textColor: "#201a2e",
    halftone: 0.5,
    halftoneSize: 7,
    levels: 5,
    dither: 0.8,
    ditherScale: 2,
    contrast: 1.2,
    grain: 0.14,
    aberration: 3,
    hue: -20,
  },
  "Sticker Pack": {
    outline: 1,
    edgeLow: 0.47,
    edgeHigh: 0.53,
    saturation: 1.55,
    grain: 0,
    wobble: 0,
    petals: 5,
  },
  "Flat Garden": {
    petals: 8,
    petalSize: 0.62,
    petalReach: 1.18,
    coreSize: 1.25,
    valley: 0.5,
    lean: 0.3,
    saturation: 1.2,
  },
  "Neon Night": {
    customBackground: true,
    background: "#07060f",
    textColor: "#f4f1ff",
    saturation: 1.7,
    contrast: 1.2,
    aberration: 3,
    grain: 0.04,
  },
  "Ink Blot": {
    customBackground: true,
    background: "#f6f5f0",
    textColor: "#0d0d0d",
    saturation: 0,
    contrast: 1.5,
    outline: 1,
    edgeLow: 0.46,
    edgeHigh: 0.5,
    grain: 0.1,
  },
  "Dreamy Soft": {
    customBackground: true,
    background: "#fbeef5",
    textColor: "#3a2340",
    edgeLow: 0.02,
    edgeHigh: 1.25,
    grain: 0.16,
    saturation: 1.2,
    petals: 6,
    flowerScale: 1.2,
  },
};

export const PRESET_NAMES = Object.keys(PRESETS);

export const SUBJECTS = { Flowers: 0, Stars: 1, Rings: 2, Grids: 3, Rays: 4, Spirals: 5, Squares: 6 };
export const SUBJECT_COUNT = Object.keys(SUBJECTS).length;
export const GRID_MODE_COUNT = 4;

export const LAYOUTS = { Trio: 0, Grid: 1, Honeycomb: 2, Scatter: 3, Ticker: 4, Poster: 5, Orbit: 6, Diagonal: 7 };
export const LAYOUT_COUNT = Object.keys(LAYOUTS).length;
export const LAYOUT_KEYS = [
  "layout",
  "cellSize",
  "jitter",
  "sizeVar",
  "density",
  "elementScale",
  "drift",
  "layoutSpin",
];

export const LAYOUT_DEFAULTS = {
  0: { cellSize: 150, jitter: 0, sizeVar: 0.3, density: 1, elementScale: 0.45, drift: 0.15, layoutSpin: 0.25 },
  1: { cellSize: 150, jitter: 0, sizeVar: 0.35, density: 1, elementScale: 0.42, drift: 0, layoutSpin: 0.2 },
  2: { cellSize: 150, jitter: 0.08, sizeVar: 0.3, density: 1, elementScale: 0.44, drift: 0, layoutSpin: 0.2 },
  3: { cellSize: 190, jitter: 0.85, sizeVar: 0.75, density: 0.55, elementScale: 0.5, drift: 0, layoutSpin: 0.3 },
  4: { cellSize: 170, jitter: 0, sizeVar: 0.3, density: 0.9, elementScale: 0.42, drift: 0.12, layoutSpin: 0.15 },
  5: { cellSize: 150, jitter: 0, sizeVar: 0.3, density: 1, elementScale: 0.45, drift: 0, layoutSpin: 0.2 },
  6: { cellSize: 150, jitter: 0, sizeVar: 0.3, density: 1, elementScale: 0.45, drift: 0, layoutSpin: 0.2 },
  7: { cellSize: 130, jitter: 0, sizeVar: 0.5, density: 1, elementScale: 0.42, drift: 0, layoutSpin: 0.2 },
};

export const DEFAULTS = { ...BASE, ...PRESETS[PRESET_NAMES[0]] };

export const FRAMES = [
  { label: "Flower wall", preset: "Flower Wall" },
  { label: "Wild meadow", preset: "Wild Meadow" },
  { label: "Flower rain", preset: "Flower Rain" },
  { label: "Pixel wall", preset: "Pixel Wall" },
];

export function frameConfig(frame) {
  const preset = PRESETS[frame.preset];
  return {
    ...BASE,
    ...LAYOUT_DEFAULTS[preset.layout ?? 0],
    ...preset,
    subject: frame.subject ?? 0,
    gridMode: 0,
  };
}
